### ISSUE TITLE
request new backdoor reverse_tcp_dns

### ISSUE THREAD

**Issue by sparta3407** [roissy/l0l#7]
hi, first thanks for this great work, so i hope that you add a new type of backdoor like reverse_tcp_dns for external hacking purpose no-ip and you know... thanks

**Comment by roissy** [comment]
@sparta3407 
hi, thank you, (: hmm,. i will try.

**Comment by sparta3407** [comment]
hell roissy ,can you put a demo video to show us everything about this thanks

**Comment by roissy** [comment]
hello @sparta3407 , Currently in beta version. stable versions can be also captured on video. (:
